export const GET_ENTRIES_SUCCESS = "GET_ENTRIES_SUCCESS";
export const GET_ENTRY_SUCCESS = "GET_ENTRY_SUCCESS";
export const EDIT_ENTRY_SUCCESS = "EDIT_ENTRY_SUCCESS";
export const ADD_ENTRY_SUCCESS = "ADD_ENTRY_SUCCESS";
export const DELETE_ENTRY_SUCCESS = "EDELETE_ENTRY_SUCCESS";
export const ERROR = "ERROR";
